### ISSUE TITLE
Use common interfaces

### ISSUE THREAD

**Issue by XedinUnknown** [bittyphp/bitty-event-manager#3]
Hi,

I know that FIG hasn't published their PSR-14 interfaces separately, and this is a problem that I came across when making my implementation. However, I have taken care of publishing them separately until FIG does that. This could make your implementation much more interoperable, and therefore usable in cross-platform modules. I suggest you take a look at [dhii/psr-14][]. If you decide to go for it, I suggest you depend on `^0.1`, since `0.1.x` is guaranteed to maintain BC with the current state of the PSR-14 spec.

[dhii/psr-14]: https://packagist.org/packages/dhii/psr-14

**Comment by bizurkur** [comment]
PSR-14 is flagged as abandoned. https://www.php-fig.org/psr/

I don't see the need for creating an additional dependency of identical code which will likely never be published by the original authors.

**Comment by XedinUnknown** [comment]
[PSR-14](https://github.com/php-fig/fig-standards/blob/master/proposed/event-dispatcher.md) has been revised, is now in Draft state, and will most likely be accepted in that form, or similar.
